"""add course material processing fields

Revision ID: 61ddf1667319
Revises: ab3bde0583e7
Create Date: 2026-08-14 13:25:59.464771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ddf1667319'
down_revision: Union[str, Sequence[str], None] = 'ab3bde0583e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_materials', sa.Column('processing_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('course_materials', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('course_materials', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_materials', 'processed_at')
    op.drop_column('course_materials', 'processing_error')
    op.drop_column('course_materials', 'processing_status')
    # ### end Alembic commands ###
